# Generated by Django 3.2.12 on 2022-02-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_match_id', models.IntegerField()),
                ('radiant_win', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('average_mmr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_player_id', models.IntegerField()),
                ('mmr', models.IntegerField(null=True)),
                ('matches', models.ManyToManyField(to='dotastats.Match')),
            ],
        ),
    ]
